FrontendFreaks/Official-Website

components/layout/site-footer.tsx

Added Footer section | Issue #13

---

components/layout/main-nav.tsx
components/layout/site-header.tsx

Fixed navbar responsive issues

---

components/layout/docs-nav.tsx

This PR contains fix to close issue #22.

fix: docs sidenav foreground color.

---

components/layout/docs-nav.tsx

This PR contains fix to close issue #22

fix: docs sidebar styles

---

components/icons.tsx
components/markdown/link.tsx
components/markdown/mdx.tsx
content/batch/learn/html/basic.mdx

feat: learn/html

---

config/sidebar.ts
content/batch/learn/js/dom.mdx
content/batch/learn/js/github-wrapper.mdx
content/batch/learn/js/google-keep.mdx
content/batch/learn/js/intro.mdx
content/batch/learn/js/wack-a-mole.mdx

feat: Js-learn

---

config/sidebar.ts
content/batch/build/interview/counter.mdx
content/batch/build/interview/like.mdx
content/batch/build/interview/star-rating.mdx
content/batch/build/interview/table.mdx
content/batch/build/interview/tabs.mdx
content/batch/build/interview/transfer-list.mdx

feat: build/interview

---

components/markdown/callout.tsx

This PR contains fix to close issue #21 by making the callout component's background transparent in dark mode.

fix: callout dark mode background color

---

app/(marketing)/page.tsx

Closes #33 
- modified page.tsx file

fix: renovate newsletter form style

---

components/mode-toggle.tsx

Closes #35 
Added some padding related tailwind classes.

bug: added padding around theme switcher

---

components/faq.tsx

Content Updation of Website based on previous website and notion

Faq Content Added

---

components/command-menu.tsx
content/batch/learn/css/grid.mdx

Fixed #48 
- [✅ ] My code follows the code style of this project.
- [✅ ] My change requires changes to the documentation.
- [ ✅] I have updated the documentation accordingly.
- [ ✅] All new and existing tests passed.
- [✅ ] This PR does not contain plagiarized content.
- [ ✅] The title of my pull request is a short description of the requested changes.
I added the source code of the CSS grid.

Added source code of CSS Grid docs

---

content/batch/learn/css/flex.mdx
content/batch/learn/html/basic.mdx

I have changed the name Trivia To Interview Question in DOCS.

I have changed the name Trivia To Interview Question in DOCS

---

components/layout/sidebar-nav.tsx

 Title content is expanding or collapsing on click Closes 

---

components/layout/site-footer.tsx
components/tracks.tsx

Closes #41 
- Changed "Our Batches" section card font size.
- Fixed "Footer" links properly not visible on hover.

PR: CSS issue on homepage - Closes #41

---

app/(batches)/layout.tsx

GitHub icon is now linked to GitHub repo "Frontend Freaks Repo"which earlier linked to the live website.

Updated layout.tsx

---

components/layout/site-header.tsx
components/mode-toggle.tsx

Closes #40
- Added a toggle to change the theme of website
#Light Mode
Before 
After
On hover
#Dark Mode
Before
After
On hover

Closes #40: Added toggle switch to change theme

---

app/(docs)/layout.tsx

added link to Github Icon

---

README.md

updated README.md : Closes #10

---

CONTRIBUTING.md

docs: CONTRIBUTING.md

---

CODE_OF_CONDUCT.md

docs: CODE_OF_CONDUCT

---

README.md

Updated the readme file to add contributors
Please add it under hacktoberfest and hacktoberfest accepted if you are merging it

Update README.md by adding contributors graph

---

config/nav.ts

Closes#88
Thanks for assigning this bug to me  @ManishBisht777

Add 'Docs' link to navigation bar

---

content/batch/learn/js/dom.mdx

- [ ✔] My code follows the code style of this project.
- [ ✔] I have updated the documentation accordingly.
- [ ✔] All new and existing tests passed.
- [ ✔] This PR does not contain plagiarized content.
- [ ✔] The title of my pull request is a short description of the requested changes.
> Missing Documentation Added 
> Closes#82

Missing Documentation Added To The JS DOm Section of Learn

---

next.config.js

Currently the build is failing because the we are using app router and it does not support default next export to get static HTML file to work with

build: build fail in gh actions

---

components/icons.tsx
components/layout/main-nav.tsx
components/layout/site-header.tsx

Closes #96 
make navbar responsive for mobile layout

fix: navbar for mobile devices

---

content/batch/learn/css/basic.mdx

- [ ✔ ] My code follows the code style of this project.
- [ ✔] I have updated the documentation accordingly.
- [ ✔] All new and existing tests passed.
- [ ✔] This PR does not contain plagiarized content.
- [ ✔] The title of my pull request is a short description of the requested changes.
**Added the comment which helps the beginner to understand different types of Image File Type**
Closes#80

Documentation Improved

---

components/code-editor.tsx
components/markdown/mdx.tsx
content/batch/learn/html/basic.mdx
package-lock.json
package.json

Added playground using "@monaco-editor/react package
It may require some ui modification but the functionality is good

added basic playground (needs modifications on ui)

---

app/(batches)/batch/[[...batchID]]/page.tsx
app/(batches)/layout.tsx
app/(docs)/layout.tsx
app/(marketing)/page.tsx
components/layout/docs-nav.tsx
components/layout/sidebar-nav.tsx
components/layout/site-header.tsx

1) Removed all unused imports
2) Added missing semicolons
3) Organised according to prettier for all files except .ts
Resloved build failed issue

Code-cleanup

---

content/batch/hire/hire.mdx
content/batch/learn/index.mdx
content/docs/index.mdx

Remove Content Layer paragraph from all pages and work in progress div

Remove Content Layer paragraph from all pages and work in progress div

---

content/batch/learn/html/basic.mdx

adding video player on HTML page

---

components/tracks.tsx

Closes #157 
@Shyam3050 thanks sir

solved css issue

---

content/batch/build/react/fundamentals.mdx
content/batch/build/react/quiz.mdx
content/batch/build/react/todo.mdx
content/batch/dsa/array.mdx
content/batch/dsa/polyfills.mdx
content/batch/learn/css/basic.mdx
content/batch/learn/css/flex.mdx
content/batch/learn/css/grid.mdx
content/batch/learn/github/intro.mdx
content/batch/learn/html/basic.mdx
content/batch/learn/js/dom.mdx
content/batch/learn/js/github-wrapper.mdx
content/batch/learn/js/google-keep.mdx
content/batch/learn/js/intro.mdx
content/batch/learn/js/wack-a-mole.mdx

Closes #142 
Fixes #142 
Removed the video from Assignment Tab, from all pages (Learn, DSA IN JS, Build, Hire)

removed video from all pages and from all tabs except learn tab

---

content/batch/dsa/advance-sorting.mdx

- [ ✔] My code follows the code style of this project.
- [✔ ] I have updated the documentation accordingly.
- [✔ ] All new and existing tests passed.
- [✔ ] This PR does not contain plagiarized content.
- [✔ ] The title of my pull request is a short description of the requested changes.
Now After Clicking On advance sorting it will sucsessully redirecting it to the advance-sorting page
#163Closes

Problem in Advance-sorting is solved

---

content/batch/dsa/recursion.mdx

added recursion part in dsa folder

---

app/(docs)/docs/[[...slug]]/page.tsx

- [] My change requires changes to the documentation.
> Hidden Text Is SuccsessFully Removed From The File

Hidden text apper

---

components/layout/site-footer.tsx

Changes the background color of footer in dark mode to distinguish footer section from above sections
**Before**
**After**

Changed the bg color of footer in dark mode

---

content/docs/getting-started.mdx

- [] My change requires changes to the documentation.
> Here in the DOCS-Get Started Section DSA card is missing and there is no WhiteBackground user for Cards
> Now I Add DSA Card In DOCS-Get Started and also add white background for Cards

DSA card missing in DOCS-Get Started

---

README.md

updated clone url and folder path. earlier url was misleading us.

readme clone url updated

---

content/batch/build/react/fundamentals.mdx

Added 10 Frequently asked React Theory Interview Questions under Build Batch > React > Fundamental > Interview Questions (New Tab)
Resolved #173 
I have added a new tab and 10 frequently asked theory interview questions of reactJS under Build Batch > React > Fundamental > Interview Questions (New Tab). Will be updating more regularly.

Feat: Added React Theory Interview Questions

---

components/layout/main-nav.tsx
config/nav.ts

Resolved #192
Just a very small fix.
In Navbar DSA IN JS does not match the style of the page and looks a bit weird. So, converting IN in small caps.

Navbar dsa button style

---

components/video-player.tsx

In small screen Youtube iframe is causing problems to the page
##Fix Explaination
Add the default aspect-ratio for the video frame. 
File Change: "components/video-player.tsx"

Fix: In small screen Youtube iframe is causing problems to the page

---

content/batch/learn/css/flex.mdx

- Added 12 interview questions on CSS Flex

Resolved #175: added interview ques for CSS Flex Crash Course

---

components/layout/site-footer.tsx

Closes #179
Earlier at footer there was button having text Mentorship which directs user to discord that is the community. So changed it's text from Mentorship to join community.

footer join community button

---

content/batch/learn/css/flex.mdx

addng interview questions in css flex course

---

content/batch/learn/css/grid.mdx

adding interview question in css grid

---

app/(marketing)/layout.tsx
components/layout/announcement-section.tsx

Close #212 
The best thing about Frontend Freaks is that it's completely free and we should highlight this fact at the very top of the website to attract and engage more people. This announcement section above the navbar lets us highlight special offers as well but currently, I'm adding it to highlight that Free feature. 
I have created a responsive section along with a dark theme with a highlight "LEARN AND BUILD EVERYTHING FOR
FREE 🚀"
https://github.com/FrontendFreaks/Official-Website/assets/65448358/c44d4c4e-9a6d-4e65-8e6a-851bf1d4a142

Feat: Added Announcement Section at the Top of main Navbar

---

content/batch/learn/html/basic.mdx

Closes issues #169 
- Added semantic tags notes 
- Included header, main, nav, article, address, aside, section and footer tags.

Added Semantic Tags notes and break line tag

---

app/(batches)/layout.tsx
app/(docs)/layout.tsx

Fixes #120
- Added <SiteFooter /> in these files: `app/batch/layout.tsx` and  `app/docs/layout.tsx`

Footer added in all pages

---

content/batch/learn/js/intro.mdx

- Added 13 frequently asked questions on JS
- Answers to ques with code snippets

Fixed: #217 Added Interview questions on JavaScript

---

content/batch/learn/html/basic.mdx

Fixes #203 
- Added two tabs for showing HTML video after the 'watch now' section in batch/learn/html. 
- One tab is for HTML in Hindi video and one is for English.

Added tabs for HTML Video in English and in Hindi

---

content/batch/learn/js/dom.mdx

- added 14 mostly asked Interview questions on DOM Manipulation
- added answers to each question 
- examples with code snippets where needed

feat: added interview questions on DOM Manipulation 

---

content/batch/learn/css/basic.mdx
content/batch/learn/css/flex.mdx
content/batch/learn/css/grid.mdx
content/batch/learn/github/intro.mdx
content/batch/learn/js/dom.mdx
content/batch/learn/js/intro.mdx

- Added video in Hindi tab at CSS intro part
- Added video in Hindi tab at CSS Flex properties part
- Added video in Hindi tab at CSS grid part
- Added video in Hindi tab at Git and GitHub section
- Added video in Hindi tab at Javascript intro and also at DOM section

Added video in Hindi at all the required places
